### PR TITLE
Rename dataclasses and serializers

### PR DESCRIPTION
**Pull request by dchiquit**
It was not obvious from the name of the dataclasses/serializers which direction data was flowing, so they are named more verbosely now.
The names are quite a mouthful, so if there are shorter suggestions that are still explicit that would be nice.

### CODE REVIEW

**Comment by brianhelba** [comment]
This is just my perspective. Feel free to disagree.

We've already started to see the internal dataclasses within `_multipart` start to diverge from the request / response serializers on the API, and I think they are logically distinct. My intuition is that we should embrace that distinction, since it will allow us to continue to add functionality at the HTTP layer without disrupting the simple operation of `_multipart`.

Could we start by changing the name of the view serializers to include the words "request" and "response"? I agree that's an unambiguously positive change.

However, `_multipart` knows nothing of "requests" and "responses". It just knows about function inputs and outputs to coordinate a multipart upload. If we want to rename the `_multipart` dataclasses, it might be better to choose language that's less suggestive of our HTTP API.

**Comment by dchiquit** [comment]
I couldn't think of any language that was unambiguous as to incoming/outgoing data. It hasn't mattered yet because we've coincidentally only had one dataclass per function, but once we start presigning we're going to have finalize taking an `UploadFinalizationArgument` and returning an `UploadFinalizationReturnValue`.

**Comment by dchiquit** [comment]
Accidentally closed, I meant to delete that comment.

**Comment by dchiquit** [comment]
I also felt bad about that, but I couldn't think of a better way to convey that some information was coming in and some was going out. I changed `UploadInitializationRequest` -> `UploadInitialization` and `UploadInitializationResponse` -> `InitializedUpload`, etc.

**Comment by brianhelba** [comment]
Agree, these new names are good, and provide more distinction between the internal and external APIs.

**Pull request merged**
